"""New Migration

Revision ID: e2c1a9065a5c
Revises: 6c13cece6af7
Create Date: 2026-01-05 08:29:26.477192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e2c1a9065a5c'
down_revision = '6c13cece6af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercommentrevision', sa.Column('is_revise_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercommentrevision', 'is_revise_completed')
    # ### end Alembic commands ###
